### PR TITLE
Wrap console logs to optionally silence output

### PR DESCRIPTION
**Pull request by skbolton**
It's a little hacky....
I explored around with creating a message state object and then calling  function and passing a state in. Messages were too varied and I realized this would work.

Let me know if you think its too much of a hack

### CODE REVIEW

**Comment by sandman45** [comment]
Love the battle cry function. Hah. Maybe we pass in a value for silent in the custom logging part?

**Comment by sandman45** [comment]
Wait maybe we add it as part of the config?  If it's not there we default the value of silent?

**Comment by sandman45** [comment]
If you agree update readme as well showing the silent value and what it is for.

**Comment by skbolton** [comment]
Yeah so the intent is that they can pass a .silent to the config and it would make battlecry() just return instead of logging. This makes it backward compatible since not passing in a .silent would just let the logging happen. I will update the readme. Should I also bump the version or how do you want  to handle that?

**Comment by skbolton** [comment]
Oh I see the confusion. I did some work and then reverted and forgot to put silent inside of Pool. I am going to squash and push again

**Pull request closed without merging**
